### ISSUE TITLE
training

### ISSUE THREAD

**Issue by ZhiyiHe1997** [ZM-Zhou/SMDE-Pytorch#1]
python train_dist.py \
                      --name MD2-Res50_192_B12_M \
                      --exp_opts options/Monodepth2/train/monodepth2-res18_192_kitti_mono.yaml \
                      --batch_size 12\
                      --beta1 0.9\
                      --epoch 20\
                      --decay_step 15\
                      --decay_rate 0.1\
                      --save_freq 10\
                      --visual_freq 2000\
                      --metric_name depth_kitti_mono
I used above paras to train model with kitti dataset , and  output metrixs are wrong , could you please tell me how to fix it ? Thanks a lot ！
# Testing Start!
# Testing Result:
    | abs_rel  |  sq_rel  |   rms    | log_rms  |    a1    |    a2    |    a3    |  scale   |
    |    0.9682|   15.1163|   19.1936|    3.4777|    0.0000|    0.0000|    0.0000|   32.1059|

**Comment by ZM-Zhou** [comment]
Hi ZhiyiHe1997,
I think it is reasonable because the network was tested with the initial weights before the training, you could let the training go on and the performance will be improved. If you just want to test the trained model you could follow `Evaluate the methods`.

**Comment by ZhiyiHe1997** [comment]
thanks for your reply, i have solved this problem
