### ISSUE TITLE
How to Download Pretrained Models?

### ISSUE THREAD

**Issue by ldkong1205** [ZM-Zhou/SMDE-Pytorch#4]
Hi @ZM-Zhou, thanks for open-sourcing this project!

Could you elaborate more on how to prepare the pretrained models? What are the passwords for accessing the Baidu Pan? Is it applicable for you to upload them to Google Drive instead? Thanks for your help!

**Comment by ZM-Zhou** [comment]
Hi ldkong1205,
Thanks for your attention. For all the Baidu Pan link, the password is "smde". The Google Drive links is going to be updated in two weeks. I holp these will be helpful.

**Comment by ldkong1205** [comment]
Thanks for your information!
